var buttonColors = ["red", "blue", "green", "yellow"];
var gamepattern = []; //list of button generated by the program
var userClickedPattern = []; // list of buttons clicked by user
var start = false; // To keep track if the game has started or not.
var level = 0; // Initial level

// Starting the game by pressing a key
$(document).on("keypress", function() {
  if (start === false) { // make sure the key is pressed for the fist time
    $("#level-title").text("Level " + level); // changing title
    nextSequence();
    start = true;
  }
})

//Checking which button is clicked by user
$(".btn").on("click", function() {
  var userChosenButton = this.id;
  userClickedPattern.push(userChosenButton);
  playSound(userChosenButton);
  animatePress(userChosenButton);
  checkAnswer(userClickedPattern.length - 1);
})


//Checking Answer
function checkAnswer(currentLevel) {
  if (userClickedPattern[currentLevel] === gamepattern[currentLevel]) { //checking most recent button
    if (userClickedPattern.length === gamepattern.length) { //checking if the user sequence is completed.
      setTimeout(function() {
        nextSequence()
      }, 1000);
    }

  } else {  // if user answer is wrong..
    console.log("wrong");
    playSound("wrong");
    $("body").addClass("game-over");
    setTimeout(function() {
      $("body").removeClass("game-over")
    }, 200);
    $("#level-title").text("Game Over, Press Any Key to Restart");

    restartGame(); // Restarting the game
  }

}

// Function generating next sequence of button
function nextSequence() {

  userClickedPattern = []; //reseting user pattern once nextSequence() is generated to ready for next level.

  var randomNumber = Math.round(Math.random() * 3);

  var randomColor = buttonColors[randomNumber];

  gamepattern.push(randomColor);

  // selecting button with same color as randomColor & playing sound
  $("#" + randomColor).fadeOut(100).fadeIn(100)
  playSound(randomColor);

  level++;
  $("#level-title").text("Level " + level);

}


//Function to play sound
function playSound(name) {
  var sound = new Audio("sounds/" + name + ".mp3");
  sound.play();
}

//Function to animate the button when pressed
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}


// Function to restart the game;
function restartGame(){
level =0;
gamepattern =[];
start = false;
}
